export { default as Dashboard } from './Dashboard'
export { default as CourseSchedule } from './CourseSchedule'
export { default as CourseManagement } from './CourseManagement'
export { default as LabManagement } from './LabManagement'
export { default as EquipmentManagement } from './EquipmentManagement'
export { default as BuildingManagement } from './BuildingManagement'
export { default as LabRoomManagement } from './LabRoomManagement'